# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# [REVISI] Judul, URL, dan deskripsi situs Anda.
# -----------------------------------------------
title: "Portofolio Rifaldi Achmad"
description: >- # Deskripsi ini akan muncul di Google
  Portofolio Data Scientist yang menampilkan proyek-proyek dalam analisis data,
  machine learning, dan visualisasi data.
url: "https://RifaldiAchmad.github.io" # [PENTING] URL situs Anda, tanpa / di akhir
baseurl: "" # Kosongkan untuk situs tipe user (username.github.io)
repository: "RifaldiAchmad/RifaldiAchmad.github.io" # [PENTING] Memperbaiki error build sebelumnya

# [REVISI] Skin theme dan username media sosial utama
# -----------------------------------------------
minimal_mistakes_skin: "air" # "air" adalah skin yang populer dan bersih. Pilihan lain: "dark", "default", "dirt"
search: true
github_username: "RifaldiAchmad"
# twitter_username: username # Tidak perlu diisi jika sudah ada di bagian author links

# Build settings
# -----------------------------------------------
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Jakarta # [REVISI] Mengatur zona waktu Indonesia

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
# -----------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# [REVISI] Informasi personal Anda akan muncul di sidebar
# -----------------------------------------------
author:
  name: "Rifaldi Achmad"
  avatar: "/assets/images/bio-photo.jpg" # Pastikan Anda sudah upload foto dengan nama ini
  bio: "Seorang Data Scientist yang antusias dalam menemukan cerita dan solusi dari data."
  location: "Indonesia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "rifaldiaf1@gmail.com" # Ganti dengan email Anda
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/rifaldiachmad" # Ganti dengan URL LinkedIn Anda
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RifaldiAchmad"

# [REVISI] Link di bagian bawah halaman (footer)
# -----------------------------------------------
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/username-linkedin-anda" # Ganti dengan URL LinkedIn Anda
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RifaldiAchmad"

# [REVISI] Pengaturan default untuk semua post dan halaman
# -----------------------------------------------
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false # Komentar bisa dinonaktifkan untuk portofolio
      share: true
      related: true
  # _pages
  - scope:
      path: "" # Mengubah dari "_pages" agar berlaku untuk semua halaman (termasuk yg di root)
      type: pages
    values:
      layout: single
      author_profile: true

# Pengaturan untuk arsip berdasarkan kategori dan tag
# -----------------------------------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
